branch-defaults:
  master:
    environment: sandbox-test
global:
  application_name: mvp-site
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
